language: ruby

cache: bundler

rvm:
- "2.5"
- "2.6"
- "2.7"

services:
- redis-server

before_script:
- bundle exec run mockserver --daemon

before_install:
- gem install bundler

script: bundle exec rspec
