language: ruby

rvm:
- "2.3.0"
- "2.5.3"

services:
- redis-server

notifications:
  email: false

before_script:
- bundle exec run mockserver --daemon

before_install:
- gem install bundler

script: bundle exec rspec
