name: Test
on:
  pull_request:
  push: { branches: master }

jobs:
  test:
    name: Ruby ${{ matrix.ruby }}
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.ruby == 'head' }}

    env: 
      CI: 1

    services:
      redis: { image: redis, ports: ["6379:6379"] }

    strategy:
      matrix:
        ruby: ['3.1', '3.2', '3.3']

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install OS dependencies
      run: sudo apt-get -y install libyaml-dev

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with: 
        ruby-version: '${{ matrix.ruby }}'
        bundler-cache: true

    - name: Start mock server
      run: |
        nohup bundle exec run mockserver &
        sleep 2

    - name: Run tests
      run: bundle exec rspec
